/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkRouteImport } from './routes/_authenticated/work'
import { Route as AuthenticatedVisionBoardRouteImport } from './routes/_authenticated/vision-board'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedRoutineRouteImport } from './routes/_authenticated/routine'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as AuthenticatedNegativeHabitsRouteImport } from './routes/_authenticated/negative-habits'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientLeadsRouteImport } from './routes/_authenticated/client-leads'
import { Route as AuthenticatedClientCallsRouteImport } from './routes/_authenticated/client-calls'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkRoute = AuthenticatedWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVisionBoardRoute =
  AuthenticatedVisionBoardRouteImport.update({
    id: '/vision-board',
    path: '/vision-board',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoutineRoute = AuthenticatedRoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNegativeHabitsRoute =
  AuthenticatedNegativeHabitsRouteImport.update({
    id: '/negative-habits',
    path: '/negative-habits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientLeadsRoute =
  AuthenticatedClientLeadsRouteImport.update({
    id: '/client-leads',
    path: '/client-leads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientCallsRoute =
  AuthenticatedClientCallsRouteImport.update({
    id: '/client-calls',
    path: '/client-calls',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/client-calls': typeof AuthenticatedClientCallsRoute
  '/client-leads': typeof AuthenticatedClientLeadsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/negative-habits': typeof AuthenticatedNegativeHabitsRoute
  '/report': typeof AuthenticatedReportRoute
  '/routine': typeof AuthenticatedRoutineRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/vision-board': typeof AuthenticatedVisionBoardRoute
  '/work': typeof AuthenticatedWorkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/client-calls': typeof AuthenticatedClientCallsRoute
  '/client-leads': typeof AuthenticatedClientLeadsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/negative-habits': typeof AuthenticatedNegativeHabitsRoute
  '/report': typeof AuthenticatedReportRoute
  '/routine': typeof AuthenticatedRoutineRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/vision-board': typeof AuthenticatedVisionBoardRoute
  '/work': typeof AuthenticatedWorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/client-calls': typeof AuthenticatedClientCallsRoute
  '/_authenticated/client-leads': typeof AuthenticatedClientLeadsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/_authenticated/negative-habits': typeof AuthenticatedNegativeHabitsRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authenticated/routine': typeof AuthenticatedRoutineRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/vision-board': typeof AuthenticatedVisionBoardRoute
  '/_authenticated/work': typeof AuthenticatedWorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/register'
    | '/calendar'
    | '/categories'
    | '/client-calls'
    | '/client-leads'
    | '/dashboard'
    | '/habits'
    | '/negative-habits'
    | '/report'
    | '/routine'
    | '/tasks'
    | '/vision-board'
    | '/work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/register'
    | '/calendar'
    | '/categories'
    | '/client-calls'
    | '/client-leads'
    | '/dashboard'
    | '/habits'
    | '/negative-habits'
    | '/report'
    | '/routine'
    | '/tasks'
    | '/vision-board'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/register'
    | '/_authenticated/calendar'
    | '/_authenticated/categories'
    | '/_authenticated/client-calls'
    | '/_authenticated/client-leads'
    | '/_authenticated/dashboard'
    | '/_authenticated/habits'
    | '/_authenticated/negative-habits'
    | '/_authenticated/report'
    | '/_authenticated/routine'
    | '/_authenticated/tasks'
    | '/_authenticated/vision-board'
    | '/_authenticated/work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/work': {
      id: '/_authenticated/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof AuthenticatedWorkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vision-board': {
      id: '/_authenticated/vision-board'
      path: '/vision-board'
      fullPath: '/vision-board'
      preLoaderRoute: typeof AuthenticatedVisionBoardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/routine': {
      id: '/_authenticated/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof AuthenticatedRoutineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negative-habits': {
      id: '/_authenticated/negative-habits'
      path: '/negative-habits'
      fullPath: '/negative-habits'
      preLoaderRoute: typeof AuthenticatedNegativeHabitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client-leads': {
      id: '/_authenticated/client-leads'
      path: '/client-leads'
      fullPath: '/client-leads'
      preLoaderRoute: typeof AuthenticatedClientLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client-calls': {
      id: '/_authenticated/client-calls'
      path: '/client-calls'
      fullPath: '/client-calls'
      preLoaderRoute: typeof AuthenticatedClientCallsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedClientCallsRoute: typeof AuthenticatedClientCallsRoute
  AuthenticatedClientLeadsRoute: typeof AuthenticatedClientLeadsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedNegativeHabitsRoute: typeof AuthenticatedNegativeHabitsRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
  AuthenticatedRoutineRoute: typeof AuthenticatedRoutineRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedVisionBoardRoute: typeof AuthenticatedVisionBoardRoute
  AuthenticatedWorkRoute: typeof AuthenticatedWorkRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedClientCallsRoute: AuthenticatedClientCallsRoute,
  AuthenticatedClientLeadsRoute: AuthenticatedClientLeadsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedNegativeHabitsRoute: AuthenticatedNegativeHabitsRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
  AuthenticatedRoutineRoute: AuthenticatedRoutineRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedVisionBoardRoute: AuthenticatedVisionBoardRoute,
  AuthenticatedWorkRoute: AuthenticatedWorkRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
